#pragma once
#include "cinder/CinderResources.h"

#define RES_SKY_VERT_GLSL                     CINDER_RESOURCE( ../resources/, sky-vert.glsl, 116, GLSL )
#define RES_SKY_FRAG_GLSL                     CINDER_RESOURCE( ../resources/, sky-frag.glsl, 117, GLSL )
#define RES_BLUR_VERT_GLSL                    CINDER_RESOURCE( ../resources/, blur-vert.glsl, 118, GLSL )
#define RES_BLUR_FRAG_GLSL                    CINDER_RESOURCE( ../resources/, blur-frag.glsl, 119, GLSL )
#define RES_MATERIAL_VERT_GLSL                CINDER_RESOURCE( ../resources/, material-vert.glsl, 120, GLSL )
#define RES_MATERIAL_FRAG_GLSL                CINDER_RESOURCE( ../resources/, material-frag.glsl, 121, GLSL )
#define RES_METABALL_VERT_GLSL                CINDER_RESOURCE( ../resources/, metaball-vert.glsl, 122, GLSL )
#define RES_METABALL_FRAG_GLSL                CINDER_RESOURCE( ../resources/, metaball-frag.glsl, 123, GLSL )
#define RES_LIGHT_CLAMP_VERT_GLSL             CINDER_RESOURCE( ../resources/, light_clamp-vert.glsl, 124, GLSL )
#define RES_LIGHT_CLAMP_FRAG_GLSL             CINDER_RESOURCE( ../resources/, light_clamp-frag.glsl, 125, GLSL )
#define RES_BLUR_HORIZONTAL_VERT_GLSL         CINDER_RESOURCE( ../resources/, blur_horizontal-vert.glsl, 126, GLSL )
#define RES_BLUR_HORIZONTAL_FRAG_GLSL         CINDER_RESOURCE( ../resources/, blur_horizontal-frag.glsl, 127, GLSL )
#define RES_BLUR_VERTICAL_VERT_GLSL           CINDER_RESOURCE( ../resources/, blur_vertical-vert.glsl, 128, GLSL )
#define RES_BLUR_VERTICAL_FRAG_GLSL           CINDER_RESOURCE( ../resources/, blur_vertical-frag.glsl, 129, GLSL )
#define RES_SCREEN_VERT_GLSL                  CINDER_RESOURCE( ../resources/, screen-vert.glsl, 130, GLSL )
#define RES_SCREEN_FRAG_GLSL                  CINDER_RESOURCE( ../resources/, screen-frag.glsl, 131, GLSL )
#define RES_FXAA_VERT_GLSL                    CINDER_RESOURCE( ../resources/, fxaa-vert.glsl, 132, GLSL )
#define RES_FXAA_FRAG_GLSL                    CINDER_RESOURCE( ../resources/, fxaa-frag.glsl, 133, GLSL )
